# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
        types:
            CallType:     AppBundle\DBAL\Types\CallType
            EventType:    AppBundle\DBAL\Types\EventType
            PlatformType: AppBundle\DBAL\Types\PlatformType
            GenderType: AppBundle\DBAL\Types\GenderType
            TournamentType: AppBundle\DBAL\Types\TournamentType
            DepartmentType: AppBundle\DBAL\Types\DepartmentType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true