sonata_media:
    db_driver: doctrine_orm
    class:
        media: AppBundle\Entity\Image
    default_context: default
    contexts:
        default:
            providers:
                - sonata.media.provider.image

            formats:
                standard:  { width: 200, quality: 100 }
                thumbnail: { width: 100,  quality: 100 }

    cdn:
        server:
            path: /uploads/media

    filesystem:
        local:
            directory: "%kernel.root_dir%/../web/uploads/media"
            create:    true

    providers:
        image:
            generator: app.generator.date

sonata_classification:

