security:
    providers:
        db:
            id: app.database_user_provider

    role_hierarchy:
        ROLE_USER: ~
        ROLE_ADMIN: [ROLE_USER]

    firewalls:
        mobile_api_auth:
            pattern: ^/api/mobile/v\d+/auth
            anonymous: ~

        mobile_api_main:
            pattern: ^/api/mobile
            stateless: true
            simple_preauth:
                authenticator: app.access_token_authenticator
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        event_api:
            pattern: ^/api/events
            anonymous: ~

        main:
            anonymous: ~

    access_control:
        - { path: ^/api/mobile/v1/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }