auth:
    type:        rest
    resource:    AppBundle\Controller\API\AuthController
    name_prefix: api_mobile_

user:
    type:        rest
    resource:    AppBundle\Controller\API\UserController
    name_prefix: api_mobile_

metric:
    type:        rest
    resource:    AppBundle\Controller\API\MetricController
    name_prefix: api_mobile_