services:
    app.generator.date:
        class: AppBundle\Generator\DateGenerator

    app.image_type_handler:
        class: AppBundle\Serializer\Handlers\ImageHandler
        arguments: ['@sonata.media.provider.image', '%base_url%']
        tags:
            - { name: jms_serializer.subscribing_handler }

    sonata.media.doctrine.event_subscriber:
        class: AppBundle\Listener\ORM\MediaEventSubscriber
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_subscriber }

    app.timestamp_type_handler:
        class: AppBundle\Serializer\Handlers\TimestampHandler
        tags:
            - { name: jms_serializer.subscribing_handler }

    app.cached_entity_type_handler:
        class: AppBundle\Serializer\Handlers\CachedEntityHandler
        tags:
            - { name: jms_serializer.subscribing_handler }

    app.exception.listener:
        class: AppBundle\EventListener\ExceptionListener
        arguments: ['@logger']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    app.request.listener:
        class: AppBundle\EventListener\RequestListener
        arguments: ['@logger']
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    app.push.listener:
        class: AppBundle\EventListener\PushEventListener
        arguments: ['%onesignal.api_key%', '%onesignal.app_id%', '@app.manager.user']
        tags:
            - { name: kernel.event_listener, event: 'app.event.push', method: 'processPush' }

    app.external_event.listener:
        class: AppBundle\EventListener\ExternalEventListener
        arguments: ['@app.handler.duel', '@app.handler.tournament']
        tags:
            - { name: kernel.event_listener, event: 'app.event.external', method: 'onExternalEvent' }

    app.access_token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
        public: false

    app.database_user_provider:
        class: AppBundle\Security\DatabaseUserProvider
        arguments: ['@app.manager.user']

    app.handler.auth:
        class: AppBundle\Handler\AuthHandler
        arguments:
            - '@app.manager.user'
            - '@app.manager.device'
            - '@app.manager.access_token'
            - '@app.manager.phone'
            - '@app.handler.user'
            - '@event_dispatcher'
            - '%main.disable_password_generation%'

    app.handler.duel:
        class: AppBundle\Handler\DuelHandler
        arguments: ['@app.manager.duel', '@app.manager.metric', '@app.handler.event']

    app.handler.user:
        class: AppBundle\Handler\UserHandler
        arguments: ['@app.manager.user', '@app.manager.access_token']

    app.handler.event:
        class: AppBundle\Handler\EventHandler
        arguments: ['@app.manager.event', '@event_dispatcher']

    app.manager.user:
        class: AppBundle\Manager\UserManager
        arguments: ['AppBundle\Entity\User', '@doctrine']

    app.handler.tournament:
        class: AppBundle\Handler\TournamentHandler
        arguments: ['@app.handler.event', '@app.manager.tournament', '@app.manager.tournament_team_participant']

    app.manager.access_token:
        class: AppBundle\Manager\AccessTokenManager
        arguments: ['AppBundle\Entity\AccessToken', '@doctrine']

    app.manager.department:
        class: AppBundle\Manager\DepartmentManager
        arguments: ['AppBundle\Entity\Department', '@doctrine']

    app.manager.device:
        class: AppBundle\Manager\DeviceManager
        arguments: ['AppBundle\Entity\Device', '@doctrine']

    app.manager.duel:
        class: AppBundle\Manager\DuelManager
        arguments: ['AppBundle\Entity\Duel', '@doctrine']

    app.manager.metric:
        class: AppBundle\Manager\MetricManager
        arguments: ['AppBundle\Entity\Metric', '@doctrine']

    app.manager.phone:
        class: AppBundle\Manager\PhoneManager
        arguments: ['AppBundle\Entity\Phone', '@doctrine']

    app.manager.event:
        class: AppBundle\Manager\EventManager
        arguments: ['AppBundle\Entity\Event', '@doctrine']

    app.manager.tournament_team_participant:
        class: AppBundle\Manager\TournamentTeamParticipantManager
        arguments: ['AppBundle\Entity\TournamentTeamParticipant', '@doctrine']

    app.manager.tournament:
        class: AppBundle\Manager\TournamentManager
        arguments: ['AppBundle\Entity\Tournament', '@doctrine']
        calls:
            - [ setUserManager, ["@app.manager.user"]]
            - [ setMetricManager, ["@app.manager.metric"]]
