services:
    app.timestamp_type_handler:
        class: AppBundle\Serializer\Handlers\TimestampHandler
        tags:
            - { name: jms_serializer.subscribing_handler }

    app.cached_entity_type_handler:
        class: AppBundle\Serializer\Handlers\CachedEntityHandler
        tags:
            - { name: jms_serializer.subscribing_handler }

    app.exception.listener:
        class: AppBundle\EventListener\ExceptionListener
        arguments: ['@logger']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    app.request.listener:
        class: AppBundle\EventListener\RequestListener
        arguments: ['@logger']
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    app.access_token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
        public: false

    app.database_user_provider:
        class: AppBundle\Security\DatabaseUserProvider
        arguments: ['@app.manager.user']

    app.handler.auth:
        class: AppBundle\Handler\AuthHandler
        arguments:
            - '@app.manager.user'
            - '@app.manager.device'
            - '@app.manager.access_token'
            - '@app.manager.phone'
            - '@app.handler.user'
            - '@event_dispatcher'
            - '%main.disable_password_generation%'

    app.handler.user:
        class: AppBundle\Handler\UserHandler
        arguments: ['@app.manager.user', '@app.manager.access_token']

    app.manager.user:
        class: AppBundle\Manager\UserManager
        arguments: ['AppBundle\Entity\User', '@doctrine']

    app.manager.access_token:
        class: AppBundle\Manager\AccessTokenManager
        arguments: ['AppBundle\Entity\AccessToken', '@doctrine']

    app.manager.department:
        class: AppBundle\Manager\DepartmentManager
        arguments: ['AppBundle\Entity\Department', '@doctrine']

    app.manager.device:
        class: AppBundle\Manager\DeviceManager
        arguments: ['AppBundle\Entity\Device', '@doctrine']

    app.manager.phone:
        class: AppBundle\Manager\PhoneManager
        arguments: ['AppBundle\Entity\Phone', '@doctrine']
